(function(window,document,$,undefined){"use strict";window.console=window.console||{info:function(stuff){}};if(!$){return;}
if($.fn.fancybox){console.info("fancyBox already initialized");return;}
var defaults={loop:false,gutter:50,keyboard:true,arrows:true,infobar:true,smallBtn:"auto",toolbar:"auto",buttons:["zoom","thumbs","close"],idleTime:3,protect:false,modal:false,image:{preload:false},ajax:{settings:{data:{fancybox:true}}},iframe:{tpl:'<iframe id="fancybox-frame{rnd}" name="fancybox-frame{rnd}" class="fancybox-iframe" frameborder="0" vspace="0" hspace="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen allowtransparency="true" src=""></iframe>',preload:true,css:{},attr:{scrolling:"auto"}},defaultType:"image",animationEffect:"zoom",animationDuration:366,zoomOpacity:"auto",transitionEffect:"fade",transitionDuration:366,slideClass:"",baseClass:"",baseTpl:'<div class="fancybox-container" role="dialog" tabindex="-1">'+
'<div class="fancybox-bg"></div>'+
'<div class="fancybox-inner">'+
'<div class="fancybox-infobar">'+
"<span data-fancybox-index></span>&nbsp;/&nbsp;<span data-fancybox-count></span>"+
"</div>"+
'<div class="fancybox-toolbar">{{buttons}}</div>'+
'<div class="fancybox-navigation">{{arrows}}</div>'+
'<div class="fancybox-stage"></div>'+
'<div class="fancybox-caption"></div>'+
"</div>"+
"</div>",spinnerTpl:'<div class="fancybox-loading"></div>',errorTpl:'<div class="fancybox-error"><p>{{ERROR}}</p></div>',btnTpl:{download:'<a download data-fancybox-download class="fancybox-button fancybox-button--download" title="{{DOWNLOAD}}" href="javascript:;">'+
'<svg viewBox="0 0 40 40">'+
'<path d="M13,16 L20,23 L27,16 M20,7 L20,23 M10,24 L10,28 L30,28 L30,24" />'+
"</svg>"+
"</a>",zoom:'<button data-fancybox-zoom class="fancybox-button fancybox-button--zoom" title="{{ZOOM}}">'+
'<svg viewBox="0 0 40 40">'+
'<path d="M18,17 m-8,0 a8,8 0 1,0 16,0 a8,8 0 1,0 -16,0 M24,22 L31,29" />'+
"</svg>"+
"</button>",close:'<button data-fancybox-close class="fancybox-button fancybox-button--close" title="{{CLOSE}}">'+
'<svg viewBox="0 0 40 40">'+
'<path d="M10,10 L30,30 M30,10 L10,30" />'+
"</svg>"+
"</button>",smallBtn:'<button data-fancybox-close class="fancybox-close-small" title="{{CLOSE}}"><svg viewBox="0 0 32 32"><path d="M10,10 L22,22 M22,10 L10,22"></path></svg></button>',arrowLeft:'<a data-fancybox-prev class="fancybox-button fancybox-button--arrow_left" title="{{PREV}}" href="javascript:;">'+
'<svg viewBox="0 0 40 40">'+
'<path d="M18,12 L10,20 L18,28 M10,20 L30,20"></path>'+
"</svg>"+
"</a>",arrowRight:'<a data-fancybox-next class="fancybox-button fancybox-button--arrow_right" title="{{NEXT}}" href="javascript:;">'+
'<svg viewBox="0 0 40 40">'+
'<path d="M10,20 L30,20 M22,12 L30,20 L22,28"></path>'+
"</svg>"+
"</a>"},parentEl:"body",autoFocus:false,backFocus:true,trapFocus:true,fullScreen:{autoStart:false},touch:{vertical:true,momentum:true},hash:null,media:{},slideShow:{autoStart:false,speed:4000},thumbs:{autoStart:false,hideOnClose:true,parentEl:".fancybox-container",axis:"y"},wheel:"auto",onInit:$.noop,beforeLoad:$.noop,afterLoad:$.noop,beforeShow:$.noop,afterShow:$.noop,beforeClose:$.noop,afterClose:$.noop,onActivate:$.noop,onDeactivate:$.noop,clickContent:function(current,event){return current.type==="image"?"zoom":false;},clickSlide:"close",clickOutside:"close",dblclickContent:false,dblclickSlide:false,dblclickOutside:false,mobile:{idleTime:false,clickContent:function(current,event){return current.type==="image"?"toggleControls":false;},clickSlide:function(current,event){return current.type==="image"?"toggleControls":"close";},dblclickContent:function(current,event){return current.type==="image"?"zoom":false;},dblclickSlide:function(current,event){return current.type==="image"?"zoom":false;}},lang:"en",i18n:{en:{CLOSE:"Close",NEXT:"Next",PREV:"Previous",ERROR:"The requested content cannot be loaded. <br/> Please try again later.",PLAY_START:"Start slideshow",PLAY_STOP:"Pause slideshow",FULL_SCREEN:"Full screen",THUMBS:"Thumbnails",DOWNLOAD:"Download",SHARE:"Share",ZOOM:"Zoom"},de:{CLOSE:"Schliessen",NEXT:"Weiter",PREV:"Zurück",ERROR:"Die angeforderten Daten konnten nicht geladen werden. <br/> Bitte versuchen Sie es später nochmal.",PLAY_START:"Diaschau starten",PLAY_STOP:"Diaschau beenden",FULL_SCREEN:"Vollbild",THUMBS:"Vorschaubilder",DOWNLOAD:"Herunterladen",SHARE:"Teilen",ZOOM:"Maßstab"}}};var $W=$(window);var $D=$(document);var called=0;var isQuery=function(obj){return obj&&obj.hasOwnProperty&&obj instanceof $;};var requestAFrame=(function(){return(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||function(callback){return window.setTimeout(callback,1000/60);});})();var transitionEnd=(function(){var el=document.createElement("fakeelement"),t;var transitions={transition:"transitionend",OTransition:"oTransitionEnd",MozTransition:"transitionend",WebkitTransition:"webkitTransitionEnd"};for(t in transitions){if(el.style[t]!==undefined){return transitions[t];}}
return "transitionend";})();var forceRedraw=function($el){return $el&&$el.length&&$el[0].offsetHeight;};var mergeOpts=function(opts1,opts2){var rez=$.extend(true,{},opts1,opts2);$.each(opts2,function(key,value){if($.isArray(value)){rez[key]=value;}});return rez;};var FancyBox=function(content,opts,index){var self=this;self.opts=mergeOpts({index:index},$.fancybox.defaults);if($.isPlainObject(opts)){self.opts=mergeOpts(self.opts,opts);}
if($.fancybox.isMobile){self.opts=mergeOpts(self.opts,self.opts.mobile);}
self.id=self.opts.id||++called;self.currIndex=parseInt(self.opts.index,10)||0;self.prevIndex=null;self.prevPos=null;self.currPos=0;self.firstRun=true;self.group=[];self.slides={};self.addContent(content);if(!self.group.length){return;}
self.$lastFocus=$(document.activeElement).trigger("blur");self.init();};$.extend(FancyBox.prototype,{init:function(){var self=this,firstItem=self.group[self.currIndex],firstItemOpts=firstItem.opts,scrollbarWidth=$.fancybox.scrollbarWidth,$scrollDiv,$container,buttonStr;if(!$.fancybox.getInstance()&&firstItemOpts.hideScrollbar!==false){$("body").addClass("fancybox-active");if(!$.fancybox.isMobile&&document.body.scrollHeight>window.innerHeight){if(scrollbarWidth===undefined){$scrollDiv=$('<div style="width:100px;height:100px;overflow:scroll;" />').appendTo("body");scrollbarWidth=$.fancybox.scrollbarWidth=$scrollDiv[0].offsetWidth-$scrollDiv[0].clientWidth;$scrollDiv.remove();}
$("head").append('<style id="fancybox-style-noscroll" type="text/css">.compensate-for-scrollbar { margin-right: '+
scrollbarWidth+
"px; }</style>");$("body").addClass("compensate-for-scrollbar");}}
buttonStr="";$.each(firstItemOpts.buttons,function(index,value){buttonStr+=firstItemOpts.btnTpl[value]||"";});$container=$(self.translate(self,firstItemOpts.baseTpl.replace("{{buttons}}",buttonStr).replace("{{arrows}}",firstItemOpts.btnTpl.arrowLeft+firstItemOpts.btnTpl.arrowRight))).attr("id","fancybox-container-"+self.id).addClass("fancybox-is-hidden").addClass(firstItemOpts.baseClass).data("FancyBox",self).appendTo(firstItemOpts.parentEl);self.$refs={container:$container};["bg","inner","infobar","toolbar","stage","caption","navigation"].forEach(function(item){self.$refs[item]=$container.find(".fancybox-"+item);});self.trigger("onInit");self.activate();self.jumpTo(self.currIndex);},translate:function(obj,str){var arr=obj.opts.i18n[obj.opts.lang];return str.replace(/\{\{(\w+)\}\}/g,function(match,n){var value=arr[n];if(value===undefined){return match;}
return value;});},addContent:function(content){var self=this,items=$.makeArray(content),thumbs;$.each(items,function(i,item){var obj={},opts={},$item,type,found,src,srcParts;if($.isPlainObject(item)){obj=item;opts=item.opts||item;}else if($.type(item)==="object"&&$(item).length){$item=$(item);opts=$item.data()||{};opts=$.extend(true,{},opts,opts.options);opts.$orig=$item;obj.src=self.opts.src||opts.src||$item.attr("href");if(!obj.type&&!obj.src){obj.type="inline";obj.src=item;}}else{obj={type:"html",src:item+""};}
obj.opts=$.extend(true,{},self.opts,opts);if($.isArray(opts.buttons)){obj.opts.buttons=opts.buttons;}
type=obj.type||obj.opts.type;src=obj.src||"";if(!type&&src){if((found=src.match(/\.(mp4|mov|ogv)((\?|#).*)?$/i))){type="video";if(!obj.opts.videoFormat){obj.opts.videoFormat="video/"+(found[1]==="ogv"?"ogg":found[1]);}}else if(src.match(/(^data:image\/[a-z0-9+\/=]*,)|(\.(jp(e|g|eg)|gif|png|bmp|webp|svg|ico)((\?|#).*)?$)/i)){type="image";}else if(src.match(/\.(pdf)((\?|#).*)?$/i)){type="iframe";}else if(src.charAt(0)==="#"){type="inline";}}
if(type){obj.type=type;}else{self.trigger("objectNeedsType",obj);}
if(!obj.contentType){obj.contentType=$.inArray(obj.type,["html","inline","ajax"])>-1?"html":obj.type;}
obj.index=self.group.length;if(obj.opts.smallBtn=="auto"){obj.opts.smallBtn=$.inArray(obj.type,["html","inline","ajax"])>-1;}
if(obj.opts.toolbar==="auto"){obj.opts.toolbar=!obj.opts.smallBtn;}
if(obj.opts.$trigger&&obj.index===self.opts.index){obj.opts.$thumb=obj.opts.$trigger.find("img:first");}
if((!obj.opts.$thumb||!obj.opts.$thumb.length)&&obj.opts.$orig){obj.opts.$thumb=obj.opts.$orig.find("img:first");}
if($.type(obj.opts.caption)==="function"){obj.opts.caption=obj.opts.caption.apply(item,[self,obj]);}
if($.type(self.opts.caption)==="function"){obj.opts.caption=self.opts.caption.apply(item,[self,obj]);}
if(!(obj.opts.caption instanceof $)){obj.opts.caption=obj.opts.caption===undefined?"":obj.opts.caption+"";}
if(obj.type==="ajax"){srcParts=src.split(/\s+/,2);if(srcParts.length>1){obj.src=srcParts.shift();obj.opts.filter=srcParts.shift();}}
if(obj.opts.modal){obj.opts=$.extend(true,obj.opts,{infobar:0,toolbar:0,smallBtn:0,keyboard:0,slideShow:0,fullScreen:0,thumbs:0,touch:0,clickContent:false,clickSlide:false,clickOutside:false,dblclickContent:false,dblclickSlide:false,dblclickOutside:false});}
self.group.push(obj);});if(Object.keys(self.slides).length){self.updateControls();thumbs=self.Thumbs;if(thumbs&&thumbs.isActive){thumbs.create();thumbs.focus();}}},addEvents:function(){var self=this;self.removeEvents();self.$refs.container.on("click.fb-close","[data-fancybox-close]",function(e){e.stopPropagation();e.preventDefault();self.close(e);}).on("touchstart.fb-prev click.fb-prev","[data-fancybox-prev]",function(e){e.stopPropagation();e.preventDefault();self.previous();}).on("touchstart.fb-next click.fb-next","[data-fancybox-next]",function(e){e.stopPropagation();e.preventDefault();self.next();}).on("click.fb","[data-fancybox-zoom]",function(e){self[self.isScaledDown()?"scaleToActual":"scaleToFit"]();});$W.on("orientationchange.fb resize.fb",function(e){if(e&&e.originalEvent&&e.originalEvent.type==="resize"){requestAFrame(function(){self.update();});}else{self.$refs.stage.hide();setTimeout(function(){self.$refs.stage.show();self.update();},$.fancybox.isMobile?600:250);}});$D.on("focusin.fb",function(e){var instance=$.fancybox?$.fancybox.getInstance():null;if(instance.isClosing||!instance.current||!instance.current.opts.trapFocus||$(e.target).hasClass("fancybox-container")||$(e.target).is(document)){return;}
if(instance&&$(e.target).css("position")!=="fixed"&&!instance.$refs.container.has(e.target).length){e.stopPropagation();instance.focus();}});$D.on("keydown.fb",function(e){var current=self.current,keycode=e.keyCode||e.which;if(!current||!current.opts.keyboard){return;}
if(e.ctrlKey||e.altKey||e.shiftKey||$(e.target).is("input")||$(e.target).is("textarea")){return;}
if(keycode===8||keycode===27){e.preventDefault();self.close(e);return;}
if(keycode===37||keycode===38){e.preventDefault();self.previous();return;}
if(keycode===39||keycode===40){e.preventDefault();self.next();return;}
self.trigger("afterKeydown",e,keycode);});if(self.group[self.currIndex].opts.idleTime){self.idleSecondsCounter=0;$D.on("mousemove.fb-idle mouseleave.fb-idle mousedown.fb-idle touchstart.fb-idle touchmove.fb-idle scroll.fb-idle keydown.fb-idle",function(e){self.idleSecondsCounter=0;if(self.isIdle){self.showControls();}
self.isIdle=false;});self.idleInterval=window.setInterval(function(){self.idleSecondsCounter++;if(self.idleSecondsCounter>=self.group[self.currIndex].opts.idleTime&&!self.isDragging){self.isIdle=true;self.idleSecondsCounter=0;self.hideControls();}},1000);}},removeEvents:function(){var self=this;$W.off("orientationchange.fb resize.fb");$D.off("focusin.fb keydown.fb .fb-idle");this.$refs.container.off(".fb-close .fb-prev .fb-next");if(self.idleInterval){window.clearInterval(self.idleInterval);self.idleInterval=null;}},previous:function(duration){return this.jumpTo(this.currPos-1,duration);},next:function(duration){return this.jumpTo(this.currPos+1,duration);},jumpTo:function(pos,duration){var self=this,groupLen=self.group.length,firstRun,loop,current,previous,canvasWidth,currentPos,transitionProps;if(self.isDragging||self.isClosing||(self.isAnimating&&self.firstRun)){return;}
pos=parseInt(pos,10);loop=self.current?self.current.opts.loop:self.opts.loop;if(!loop&&(pos<0||pos>=groupLen)){return false;}
firstRun=self.firstRun=!Object.keys(self.slides).length;if(groupLen<2&&!firstRun&&!!self.isDragging){return;}
previous=self.current;self.prevIndex=self.currIndex;self.prevPos=self.currPos;current=self.createSlide(pos);if(groupLen>1){if(loop||current.index>0){self.createSlide(pos-1);}
if(loop||current.index<groupLen-1){self.createSlide(pos+1);}}
self.current=current;self.currIndex=current.index;self.currPos=current.pos;self.trigger("beforeShow",firstRun);self.updateControls();currentPos=$.fancybox.getTranslate(current.$slide);current.isMoved=(currentPos.left!==0||currentPos.top!==0)&&!current.$slide.hasClass("fancybox-animated");current.forcedDuration=undefined;if($.isNumeric(duration)){current.forcedDuration=duration;}else{duration=current.opts[firstRun?"animationDuration":"transitionDuration"];}
duration=parseInt(duration,10);if(firstRun){if(current.opts.animationEffect&&duration){self.$refs.container.css("transition-duration",duration+"ms");}
self.$refs.container.removeClass("fancybox-is-hidden");forceRedraw(self.$refs.container);self.$refs.container.addClass("fancybox-is-open");forceRedraw(self.$refs.container);current.$slide.addClass("fancybox-slide--previous");self.loadSlide(current);current.$slide.removeClass("fancybox-slide--previous").addClass("fancybox-slide--current");self.preload("image");return;}
$.each(self.slides,function(index,slide){$.fancybox.stop(slide.$slide);});current.$slide.removeClass("fancybox-slide--next fancybox-slide--previous").addClass("fancybox-slide--current");if(current.isMoved){canvasWidth=Math.round(current.$slide.width());$.each(self.slides,function(index,slide){var pos=slide.pos-current.pos;$.fancybox.animate(slide.$slide,{top:0,left:pos*canvasWidth+pos*slide.opts.gutter},duration,function(){slide.$slide.removeAttr("style").removeClass("fancybox-slide--next fancybox-slide--previous");if(slide.pos===self.currPos){current.isMoved=false;self.complete();}});});}else{self.$refs.stage.children().removeAttr("style");}
if(current.isLoaded){self.revealContent(current);}else{self.loadSlide(current);}
self.preload("image");if(previous.pos===current.pos){return;}
transitionProps="fancybox-slide--"+(previous.pos>current.pos?"next":"previous");previous.$slide.removeClass("fancybox-slide--complete fancybox-slide--current fancybox-slide--next fancybox-slide--previous");previous.isComplete=false;if(!duration||(!current.isMoved&&!current.opts.transitionEffect)){return;}
if(current.isMoved){previous.$slide.addClass(transitionProps);}else{transitionProps="fancybox-animated "+transitionProps+" fancybox-fx-"+current.opts.transitionEffect;$.fancybox.animate(previous.$slide,transitionProps,duration,function(){previous.$slide.removeClass(transitionProps).removeAttr("style");});}},createSlide:function(pos){var self=this,$slide,index;index=pos%self.group.length;index=index<0?self.group.length+index:index;if(!self.slides[pos]&&self.group[index]){$slide=$('<div class="fancybox-slide"></div>').appendTo(self.$refs.stage);self.slides[pos]=$.extend(true,{},self.group[index],{pos:pos,$slide:$slide,isLoaded:false});self.updateSlide(self.slides[pos]);}
return self.slides[pos];},scaleToActual:function(x,y,duration){var self=this,current=self.current,$content=current.$content,canvasWidth=$.fancybox.getTranslate(current.$slide).width,canvasHeight=$.fancybox.getTranslate(current.$slide).height,newImgWidth=current.width,newImgHeight=current.height,imgPos,posX,posY,scaleX,scaleY;if(self.isAnimating||!$content||!(current.type=="image"&&current.isLoaded&&!current.hasError)){return;}
$.fancybox.stop($content);self.isAnimating=true;x=x===undefined?canvasWidth*0.5:x;y=y===undefined?canvasHeight*0.5:y;imgPos=$.fancybox.getTranslate($content);imgPos.top-=$.fancybox.getTranslate(current.$slide).top;imgPos.left-=$.fancybox.getTranslate(current.$slide).left;scaleX=newImgWidth/imgPos.width;scaleY=newImgHeight/imgPos.height;posX=canvasWidth*0.5-newImgWidth*0.5;posY=canvasHeight*0.5-newImgHeight*0.5;if(newImgWidth>canvasWidth){posX=imgPos.left*scaleX-(x*scaleX-x);if(posX>0){posX=0;}
if(posX<canvasWidth-newImgWidth){posX=canvasWidth-newImgWidth;}}
if(newImgHeight>canvasHeight){posY=imgPos.top*scaleY-(y*scaleY-y);if(posY>0){posY=0;}
if(posY<canvasHeight-newImgHeight){posY=canvasHeight-newImgHeight;}}
self.updateCursor(newImgWidth,newImgHeight);$.fancybox.animate($content,{top:posY,left:posX,scaleX:scaleX,scaleY:scaleY},duration||330,function(){self.isAnimating=false;});if(self.SlideShow&&self.SlideShow.isActive){self.SlideShow.stop();}},scaleToFit:function(duration){var self=this,current=self.current,$content=current.$content,end;if(self.isAnimating||!$content||!(current.type=="image"&&current.isLoaded&&!current.hasError)){return;}
$.fancybox.stop($content);self.isAnimating=true;end=self.getFitPos(current);self.updateCursor(end.width,end.height);$.fancybox.animate($content,{top:end.top,left:end.left,scaleX:end.width/$content.width(),scaleY:end.height/$content.height()},duration||330,function(){self.isAnimating=false;});},getFitPos:function(slide){var self=this,$content=slide.$content,width=slide.width||slide.opts.width,height=slide.height||slide.opts.height,maxWidth,maxHeight,minRatio,margin,aspectRatio,rez={};if(!slide.isLoaded||!$content||!$content.length){return false;}
margin={top:parseInt(slide.$slide.css("paddingTop"),10),right:parseInt(slide.$slide.css("paddingRight"),10),bottom:parseInt(slide.$slide.css("paddingBottom"),10),left:parseInt(slide.$slide.css("paddingLeft"),10)};maxWidth=parseInt(self.$refs.stage.width(),10)-(margin.left+margin.right);maxHeight=parseInt(self.$refs.stage.height(),10)-(margin.top+margin.bottom);if(!width||!height){width=maxWidth;height=maxHeight;}
minRatio=Math.min(1,maxWidth/width,maxHeight/height);width=Math.floor(minRatio*width);height=Math.floor(minRatio*height);if(slide.type==="image"){rez.top=Math.floor((maxHeight-height)*0.5)+margin.top;rez.left=Math.floor((maxWidth-width)*0.5)+margin.left;}else if(slide.contentType==="video"){aspectRatio=slide.opts.width&&slide.opts.height?width/height:slide.opts.ratio||16/9;if(height>width/aspectRatio){height=width/aspectRatio;}else if(width>height*aspectRatio){width=height*aspectRatio;}}
rez.width=width;rez.height=height;return rez;},update:function(){var self=this;$.each(self.slides,function(key,slide){self.updateSlide(slide);});},updateSlide:function(slide,duration){var self=this,$content=slide&&slide.$content,width=slide.width||slide.opts.width,height=slide.height||slide.opts.height;if($content&&(width||height||slide.contentType==="video")&&!slide.hasError){$.fancybox.stop($content);$.fancybox.setTranslate($content,self.getFitPos(slide));if(slide.pos===self.currPos){self.isAnimating=false;self.updateCursor();}}
slide.$slide.trigger("refresh");self.$refs.toolbar.toggleClass("compensate-for-scrollbar",slide.$slide.get(0).scrollHeight>slide.$slide.get(0).clientHeight);self.trigger("onUpdate",slide);},centerSlide:function(slide,duration){var self=this,canvasWidth,pos;if(self.current){canvasWidth=Math.round(slide.$slide.width());pos=slide.pos-self.current.pos;$.fancybox.animate(slide.$slide,{top:0,left:pos*canvasWidth+pos*slide.opts.gutter,opacity:1},duration===undefined?0:duration,null,false);}},updateCursor:function(nextWidth,nextHeight){var self=this,current=self.current,$container=self.$refs.container.removeClass("fancybox-is-zoomable fancybox-can-zoomIn fancybox-can-drag fancybox-can-zoomOut"),isZoomable;if(!current||self.isClosing){return;}
isZoomable=self.isZoomable();$container.toggleClass("fancybox-is-zoomable",isZoomable);$("[data-fancybox-zoom]").prop("disabled",!isZoomable);if(isZoomable&&(current.opts.clickContent==="zoom"||($.isFunction(current.opts.clickContent)&&current.opts.clickContent(current)==="zoom"))){if(self.isScaledDown(nextWidth,nextHeight)){$container.addClass("fancybox-can-zoomIn");}else{if(current.opts.touch){$container.addClass("fancybox-can-drag");}else{$container.addClass("fancybox-can-zoomOut");}}}else if(current.opts.touch&&current.contentType!=="video"){$container.addClass("fancybox-can-drag");}},isZoomable:function(){var self=this,current=self.current,fitPos;if(current&&!self.isClosing&&current.type==="image"&&!current.hasError){if(!current.isLoaded){return true;}
fitPos=self.getFitPos(current);if(current.width>fitPos.width||current.height>fitPos.height){return true;}}
return false;},isScaledDown:function(nextWidth,nextHeight){var self=this,rez=false,current=self.current,$content=current.$content;if(nextWidth!==undefined&&nextHeight!==undefined){rez=nextWidth<current.width&&nextHeight<current.height;}else if($content){rez=$.fancybox.getTranslate($content);rez=rez.width<current.width&&rez.height<current.height;}
return rez;},canPan:function(){var self=this,rez=false,current=self.current,$content;if(current.type==="image"&&($content=current.$content)&&!current.hasError){rez=self.getFitPos(current);rez=Math.abs($content.width()-rez.width)>1||Math.abs($content.height()-rez.height)>1;}
return rez;},loadSlide:function(slide){var self=this,type,$slide,ajaxLoad;if(slide.isLoading||slide.isLoaded){return;}
slide.isLoading=true;self.trigger("beforeLoad",slide);type=slide.type;$slide=slide.$slide;$slide.off("refresh").trigger("onReset").addClass(slide.opts.slideClass);switch(type){case "image":self.setImage(slide);break;case "iframe":self.setIframe(slide);break;case "html":self.setContent(slide,slide.src||slide.content);break;case "video":self.setContent(slide,'<video class="fancybox-video" controls controlsList="nodownload">'+
'<source src="'+
slide.src+
'" type="'+
slide.opts.videoFormat+
'">'+
"Your browser doesn't support HTML5 video"+
"</video");break;case "inline":if($(slide.src).length){self.setContent(slide,$(slide.src));}else{self.setError(slide);}
break;case "ajax":self.showLoading(slide);ajaxLoad=$.ajax($.extend({},slide.opts.ajax.settings,{url:slide.src,success:function(data,textStatus){if(textStatus==="success"){self.setContent(slide,data);}},error:function(jqXHR,textStatus){if(jqXHR&&textStatus!=="abort"){self.setError(slide);}}}));$slide.one("onReset",function(){ajaxLoad.abort();});break;default:self.setError(slide);break;}
return true;},setImage:function(slide){var self=this,srcset=slide.opts.srcset||slide.opts.image.srcset,thumbSrc,found,temp,pxRatio,windowWidth;slide.timouts=setTimeout(function(){var $img=slide.$image;if(slide.isLoading&&(!$img||!$img[0].complete)&&!slide.hasError){self.showLoading(slide);}},350);if(srcset){pxRatio=window.devicePixelRatio||1;windowWidth=window.innerWidth*pxRatio;temp=srcset.split(",").map(function(el){var ret={};el.trim().split(/\s+/).forEach(function(el,i){var value=parseInt(el.substring(0,el.length-1),10);if(i===0){return(ret.url=el);}
if(value){ret.value=value;ret.postfix=el[el.length-1];}});return ret;});temp.sort(function(a,b){return a.value-b.value;});for(var j=0;j<temp.length;j++){var el=temp[j];if((el.postfix==="w"&&el.value>=windowWidth)||(el.postfix==="x"&&el.value>=pxRatio)){found=el;break;}}
if(!found&&temp.length){found=temp[temp.length-1];}
if(found){slide.src=found.url;if(slide.width&&slide.height&&found.postfix=="w"){slide.height=slide.width/slide.height*found.value;slide.width=found.value;}
slide.opts.srcset=srcset;}}
slide.$content=$('<div class="fancybox-content"></div>').addClass("fancybox-is-hidden").appendTo(slide.$slide.addClass("fancybox-slide--image"));thumbSrc=slide.opts.thumb||(slide.opts.$thumb&&slide.opts.$thumb.length?slide.opts.$thumb.attr("src"):false);if(slide.opts.preload!==false&&slide.opts.width&&slide.opts.height&&thumbSrc){slide.width=slide.opts.width;slide.height=slide.opts.height;slide.$ghost=$("<img />").one("error",function(){$(this).remove();slide.$ghost=null;}).one("load",function(){self.afterLoad(slide);}).addClass("fancybox-image").appendTo(slide.$content).attr("src",thumbSrc);}
self.setBigImage(slide);},setBigImage:function(slide){var self=this,$img=$("<img />");slide.$image=$img.one("error",function(){self.setError(slide);}).one("load",function(){var sizes;if(!slide.$ghost){self.resolveImageSlideSize(slide,this.naturalWidth,this.naturalHeight);self.afterLoad(slide);}
if(slide.timouts){clearTimeout(slide.timouts);slide.timouts=null;}
if(self.isClosing){return;}
if(slide.opts.srcset){sizes=slide.opts.sizes;if(!sizes||sizes==="auto"){sizes=(slide.width/slide.height>1&&$W.width()/$W.height()>1?"100":Math.round(slide.width/slide.height*100))+
"vw";}
$img.attr("sizes",sizes).attr("srcset",slide.opts.srcset);}
if(slide.$ghost){setTimeout(function(){if(slide.$ghost&&!self.isClosing){slide.$ghost.hide();}},Math.min(300,Math.max(1000,slide.height/1600)));}
self.hideLoading(slide);}).addClass("fancybox-image").attr("src",slide.src).appendTo(slide.$content);if(($img[0].complete||$img[0].readyState=="complete")&&$img[0].naturalWidth&&$img[0].naturalHeight){$img.trigger("load");}else if($img[0].error){$img.trigger("error");}},resolveImageSlideSize:function(slide,imgWidth,imgHeight){var maxWidth=parseInt(slide.opts.width,10),maxHeight=parseInt(slide.opts.height,10);slide.width=imgWidth;slide.height=imgHeight;if(maxWidth>0){slide.width=maxWidth;slide.height=Math.floor(maxWidth*imgHeight/imgWidth);}
if(maxHeight>0){slide.width=Math.floor(maxHeight*imgWidth/imgHeight);slide.height=maxHeight;}},setIframe:function(slide){var self=this,opts=slide.opts.iframe,$slide=slide.$slide,$iframe;slide.$content=$('<div class="fancybox-content'+(opts.preload?" fancybox-is-hidden":"")+'"></div>').css(opts.css).appendTo($slide);$slide.addClass("fancybox-slide--"+slide.contentType);slide.$iframe=$iframe=$(opts.tpl.replace(/\{rnd\}/g,new Date().getTime())).attr(opts.attr).appendTo(slide.$content);if(opts.preload){self.showLoading(slide);$iframe.on("load.fb error.fb",function(e){this.isReady=1;slide.$slide.trigger("refresh");self.afterLoad(slide);});$slide.on("refresh.fb",function(){var $content=slide.$content,frameWidth=opts.css.width,frameHeight=opts.css.height,$contents,$body;if($iframe[0].isReady!==1){return;}
try{$contents=$iframe.contents();$body=$contents.find("body");}catch(ignore){}
if($body&&$body.length&&$body.children().length){$content.css({width:"",height:""});if(frameWidth===undefined){frameWidth=Math.ceil(Math.max($body[0].clientWidth,$body.outerWidth(true)));}
if(frameWidth){$content.width(frameWidth);}
if(frameHeight===undefined){frameHeight=Math.ceil(Math.max($body[0].clientHeight,$body.outerHeight(true)));}
if(frameHeight){$content.height(frameHeight);}}
$content.removeClass("fancybox-is-hidden");});}else{this.afterLoad(slide);}
$iframe.attr("src",slide.src);$slide.one("onReset",function(){try{$(this).find("iframe").hide().unbind().attr("src","//about:blank");}catch(ignore){}
$(this).off("refresh.fb").empty();slide.isLoaded=false;});},setContent:function(slide,content){var self=this;if(self.isClosing){return;}
self.hideLoading(slide);if(slide.$content){$.fancybox.stop(slide.$content);}
slide.$slide.empty();if(isQuery(content)&&content.parent().length){content.parent().parent(".fancybox-slide--inline").trigger("onReset");slide.$placeholder=$("<div>").hide().insertAfter(content);content.css("display","inline-block");}else if(!slide.hasError){if($.type(content)==="string"){content=$("<div>").append($.trim(content)).contents();if(content[0].nodeType===3){content=$("<div>").html(content);}}
if(slide.opts.filter){content=$("<div>").html(content).find(slide.opts.filter);}}
slide.$slide.one("onReset",function(){$(this).find("video,audio").trigger("pause");if(slide.$placeholder){slide.$placeholder.after(content.hide()).remove();slide.$placeholder=null;}
if(slide.$smallBtn){slide.$smallBtn.remove();slide.$smallBtn=null;}
if(!slide.hasError){$(this).empty();slide.isLoaded=false;}});$(content).appendTo(slide.$slide);if($(content).is("video,audio")){$(content).addClass("fancybox-video");$(content).wrap("<div></div>");slide.contentType="video";slide.opts.width=slide.opts.width||$(content).attr("width");slide.opts.height=slide.opts.height||$(content).attr("height");}
slide.$content=slide.$slide.children().filter("div,form,main,video,audio").first().addClass("fancybox-content");slide.$slide.addClass("fancybox-slide--"+slide.contentType);this.afterLoad(slide);},setError:function(slide){slide.hasError=true;slide.$slide.trigger("onReset").removeClass("fancybox-slide--"+slide.contentType).addClass("fancybox-slide--error");slide.contentType="html";this.setContent(slide,this.translate(slide,slide.opts.errorTpl));if(slide.pos===this.currPos){this.isAnimating=false;}},showLoading:function(slide){var self=this;slide=slide||self.current;if(slide&&!slide.$spinner){slide.$spinner=$(self.translate(self,self.opts.spinnerTpl)).appendTo(slide.$slide);}},hideLoading:function(slide){var self=this;slide=slide||self.current;if(slide&&slide.$spinner){slide.$spinner.remove();delete slide.$spinner;}},afterLoad:function(slide){var self=this;if(self.isClosing){return;}
slide.isLoading=false;slide.isLoaded=true;self.trigger("afterLoad",slide);self.hideLoading(slide);if(slide.pos===self.currPos){self.updateCursor();}
if(slide.opts.smallBtn&&(!slide.$smallBtn||!slide.$smallBtn.length)){slide.$smallBtn=$(self.translate(slide,slide.opts.btnTpl.smallBtn)).prependTo(slide.$content);}
if(slide.opts.protect&&slide.$content&&!slide.hasError){slide.$content.on("contextmenu.fb",function(e){if(e.button==2){e.preventDefault();}
return true;});if(slide.type==="image"){$('<div class="fancybox-spaceball"></div>').appendTo(slide.$content);}}
self.revealContent(slide);},revealContent:function(slide){var self=this,$slide=slide.$slide,end=false,start=false,effect,effectClassName,duration,opacity;effect=slide.opts[self.firstRun?"animationEffect":"transitionEffect"];duration=slide.opts[self.firstRun?"animationDuration":"transitionDuration"];duration=parseInt(slide.forcedDuration===undefined?duration:slide.forcedDuration,10);if(slide.pos===self.currPos){if(slide.isComplete){effect=false;}else{self.isAnimating=true;}}
if(slide.isMoved||slide.pos!==self.currPos||!duration){effect=false;}
if(effect==="zoom"){if(slide.pos===self.currPos&&duration&&slide.type==="image"&&!slide.hasError&&(start=self.getThumbPos(slide))){end=self.getFitPos(slide);}else{effect="fade";}}
if(effect==="zoom"){end.scaleX=end.width/start.width;end.scaleY=end.height/start.height;opacity=slide.opts.zoomOpacity;if(opacity=="auto"){opacity=Math.abs(slide.width/slide.height-start.width/start.height)>0.1;}
if(opacity){start.opacity=0.1;end.opacity=1;}
$.fancybox.setTranslate(slide.$content.removeClass("fancybox-is-hidden"),start);forceRedraw(slide.$content);$.fancybox.animate(slide.$content,end,duration,function(){self.isAnimating=false;self.complete();});return;}
self.updateSlide(slide);if(!effect){forceRedraw($slide);slide.$content.removeClass("fancybox-is-hidden");if(slide.pos===self.currPos){self.complete();}
return;}
$.fancybox.stop($slide);effectClassName="fancybox-animated fancybox-slide--"+(slide.pos>=self.prevPos?"next":"previous")+" fancybox-fx-"+effect;$slide.removeAttr("style").removeClass("fancybox-slide--current fancybox-slide--next fancybox-slide--previous").addClass(effectClassName);slide.$content.removeClass("fancybox-is-hidden");forceRedraw($slide);$.fancybox.animate($slide,"fancybox-slide--current",duration,function(e){$slide.removeClass(effectClassName).removeAttr("style");if(slide.pos===self.currPos){self.complete();}},true);},getThumbPos:function(slide){var self=this,rez=false,$thumb=slide.opts.$thumb,thumbPos=$thumb&&$thumb.length&&$thumb[0].ownerDocument===document?$thumb.offset():0,slidePos;var isElementVisible=function($el){var element=$el[0],elementRect=element.getBoundingClientRect(),parentRects=[],visibleInAllParents;while(element.parentElement!==null){if($(element.parentElement).css("overflow")==="hidden"||$(element.parentElement).css("overflow")==="auto"){parentRects.push(element.parentElement.getBoundingClientRect());}
element=element.parentElement;}
visibleInAllParents=parentRects.every(function(parentRect){var visiblePixelX=Math.min(elementRect.right,parentRect.right)-Math.max(elementRect.left,parentRect.left);var visiblePixelY=Math.min(elementRect.bottom,parentRect.bottom)-Math.max(elementRect.top,parentRect.top);return visiblePixelX>0&&visiblePixelY>0;});return(visibleInAllParents&&elementRect.bottom>0&&elementRect.right>0&&elementRect.left<$(window).width()&&elementRect.top<$(window).height());};if(thumbPos&&isElementVisible($thumb)){slidePos=self.$refs.stage.offset();rez={top:thumbPos.top-slidePos.top+parseFloat($thumb.css("border-top-width")||0),left:thumbPos.left-slidePos.left+parseFloat($thumb.css("border-left-width")||0),width:$thumb.width(),height:$thumb.height(),scaleX:1,scaleY:1};}
return rez;},complete:function(){var self=this,current=self.current,slides={};if(current.isMoved||!current.isLoaded){return;}
if(!current.isComplete){current.isComplete=true;current.$slide.siblings().trigger("onReset");self.preload("inline");forceRedraw(current.$slide);current.$slide.addClass("fancybox-slide--complete");$.each(self.slides,function(key,slide){if(slide.pos>=self.currPos-1&&slide.pos<=self.currPos+1){slides[slide.pos]=slide;}else if(slide){$.fancybox.stop(slide.$slide);slide.$slide.off().remove();}});self.slides=slides;}
self.isAnimating=false;self.updateCursor();self.trigger("afterShow");current.$slide.find("video,audio").filter(":visible:first").trigger("play");if($(document.activeElement).is("[disabled]")||(current.opts.autoFocus&&!(current.type=="image"||current.type==="iframe"))){self.focus();}},preload:function(type){var self=this,next=self.slides[self.currPos+1],prev=self.slides[self.currPos-1];if(next&&next.type===type){self.loadSlide(next);}
if(prev&&prev.type===type){self.loadSlide(prev);}},focus:function(){var current=this.current,$el;if(this.isClosing){return;}
if(current&&current.isComplete&&current.$content){$el=current.$content.find("input[autofocus]:enabled:visible:first");if(!$el.length){$el=current.$content.find("button,:input,[tabindex],a").filter(":enabled:visible:first");}
$el=$el&&$el.length?$el:current.$content;$el.trigger("focus");}},activate:function(){var self=this;$(".fancybox-container").each(function(){var instance=$(this).data("FancyBox");if(instance&&instance.id!==self.id&&!instance.isClosing){instance.trigger("onDeactivate");instance.removeEvents();instance.isVisible=false;}});self.isVisible=true;if(self.current||self.isIdle){self.update();self.updateControls();}
self.trigger("onActivate");self.addEvents();},close:function(e,d){var self=this,current=self.current,effect,duration,$content,domRect,opacity,start,end;var done=function(){self.cleanUp(e);};if(self.isClosing){return false;}
self.isClosing=true;if(self.trigger("beforeClose",e)===false){self.isClosing=false;requestAFrame(function(){self.update();});return false;}
self.removeEvents();if(current.timouts){clearTimeout(current.timouts);}
$content=current.$content;effect=current.opts.animationEffect;duration=$.isNumeric(d)?d:effect?current.opts.animationDuration:0;current.$slide.off(transitionEnd).removeClass("fancybox-slide--complete fancybox-slide--next fancybox-slide--previous fancybox-animated");current.$slide.siblings().trigger("onReset").remove();if(duration){self.$refs.container.removeClass("fancybox-is-open").addClass("fancybox-is-closing");}
self.hideLoading(current);self.hideControls();self.updateCursor();if(effect==="zoom"&&!(e!==true&&$content&&duration&&current.type==="image"&&!current.hasError&&(end=self.getThumbPos(current)))){effect="fade";}
if(effect==="zoom"){$.fancybox.stop($content);domRect=$.fancybox.getTranslate($content);start={top:domRect.top,left:domRect.left,scaleX:domRect.width/end.width,scaleY:domRect.height/end.height,width:end.width,height:end.height};opacity=current.opts.zoomOpacity;if(opacity=="auto"){opacity=Math.abs(current.width/current.height-end.width/end.height)>0.1;}
if(opacity){end.opacity=0;}
$.fancybox.setTranslate($content,start);forceRedraw($content);$.fancybox.animate($content,end,duration,done);return true;}
if(effect&&duration){if(e===true){setTimeout(done,duration);}else{$.fancybox.animate(current.$slide.removeClass("fancybox-slide--current"),"fancybox-animated fancybox-slide--previous fancybox-fx-"+effect,duration,done);}}else{done();}
return true;},cleanUp:function(e){var self=this,$body=$("body"),instance,scrollTop;self.current.$slide.trigger("onReset");self.$refs.container.empty().remove();self.trigger("afterClose",e);if(self.$lastFocus&&!!self.current.opts.backFocus){self.$lastFocus.trigger("focus");}
self.current=null;instance=$.fancybox.getInstance();if(instance){instance.activate();}else{$body.removeClass("fancybox-active compensate-for-scrollbar");$("#fancybox-style-noscroll").remove();}},trigger:function(name,slide){var args=Array.prototype.slice.call(arguments,1),self=this,obj=slide&&slide.opts?slide:self.current,rez;if(obj){args.unshift(obj);}else{obj=self;}
args.unshift(self);if($.isFunction(obj.opts[name])){rez=obj.opts[name].apply(obj,args);}
if(rez===false){return rez;}
if(name==="afterClose"||!self.$refs){$D.trigger(name+".fb",args);}else{self.$refs.container.trigger(name+".fb",args);}},updateControls:function(force){var self=this,current=self.current,index=current.index,caption=current.opts.caption,$container=self.$refs.container,$caption=self.$refs.caption;current.$slide.trigger("refresh");self.$caption=caption&&caption.length?$caption.html(caption):null;if(!self.isHiddenControls&&!self.isIdle){self.showControls();}
$container.find("[data-fancybox-count]").html(self.group.length);$container.find("[data-fancybox-index]").html(index+1);$container.find("[data-fancybox-prev]").toggleClass("disabled",!current.opts.loop&&index<=0);$container.find("[data-fancybox-next]").toggleClass("disabled",!current.opts.loop&&index>=self.group.length-1);if(current.type==="image"){$container.find("[data-fancybox-zoom]").show().end().find("[data-fancybox-download]").attr("href",current.opts.image.src||current.src).show();}else if(current.opts.toolbar){$container.find("[data-fancybox-download],[data-fancybox-zoom]").hide();}},hideControls:function(){this.isHiddenControls=true;this.$refs.container.removeClass("fancybox-show-infobar fancybox-show-toolbar fancybox-show-caption fancybox-show-nav");},showControls:function(){var self=this,opts=self.current?self.current.opts:self.opts,$container=self.$refs.container;self.isHiddenControls=false;self.idleSecondsCounter=0;$container.toggleClass("fancybox-show-toolbar",!!(opts.toolbar&&opts.buttons)).toggleClass("fancybox-show-infobar",!!(opts.infobar&&self.group.length>1)).toggleClass("fancybox-show-nav",!!(opts.arrows&&self.group.length>1)).toggleClass("fancybox-is-modal",!!opts.modal);if(self.$caption){$container.addClass("fancybox-show-caption ");}else{$container.removeClass("fancybox-show-caption");}},toggleControls:function(){if(this.isHiddenControls){this.showControls();}else{this.hideControls();}}});$.fancybox={version:"{fancybox-version}",defaults:defaults,getInstance:function(command){var instance=$('.fancybox-container:not(".fancybox-is-closing"):last').data("FancyBox"),args=Array.prototype.slice.call(arguments,1);if(instance instanceof FancyBox){if($.type(command)==="string"){instance[command].apply(instance,args);}else if($.type(command)==="function"){command.apply(instance,args);}
return instance;}
return false;},open:function(items,opts,index){return new FancyBox(items,opts,index);},close:function(all){var instance=this.getInstance();if(instance){instance.close();if(all===true){this.close();}}},destroy:function(){this.close(true);$D.add("body").off("click.fb-start","**");},isMobile:document.createTouch!==undefined&&/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),use3d:(function(){var div=document.createElement("div");return(window.getComputedStyle&&window.getComputedStyle(div)&&window.getComputedStyle(div).getPropertyValue("transform")&&!(document.documentMode&&document.documentMode<11));})(),getTranslate:function($el){var domRect;if(!$el||!$el.length){return false;}
domRect=$el[0].getBoundingClientRect();return{top:domRect.top||0,left:domRect.left||0,width:domRect.width,height:domRect.height,opacity:parseFloat($el.css("opacity"))};},setTranslate:function($el,props){var str="",css={};if(!$el||!props){return;}
if(props.left!==undefined||props.top!==undefined){str=(props.left===undefined?$el.position().left:props.left)+
"px, "+
(props.top===undefined?$el.position().top:props.top)+
"px";if(this.use3d){str="translate3d("+str+", 0px)";}else{str="translate("+str+")";}}
if(props.scaleX!==undefined&&props.scaleY!==undefined){str=(str.length?str+" ":"")+"scale("+props.scaleX+", "+props.scaleY+")";}
if(str.length){css.transform=str;}
if(props.opacity!==undefined){css.opacity=props.opacity;}
if(props.width!==undefined){css.width=props.width;}
if(props.height!==undefined){css.height=props.height;}
return $el.css(css);},animate:function($el,to,duration,callback,leaveAnimationName){var final=false;if($.isFunction(duration)){callback=duration;duration=null;}
if(!$.isPlainObject(to)){$el.removeAttr("style");}
$.fancybox.stop($el);$el.on(transitionEnd,function(e){if(e&&e.originalEvent&&(!$el.is(e.originalEvent.target)||e.originalEvent.propertyName=="z-index")){return;}
$.fancybox.stop($el);if(final){$.fancybox.setTranslate($el,final);}
if($.isPlainObject(to)){if(leaveAnimationName===false){$el.removeAttr("style");}}else if(leaveAnimationName!==true){$el.removeClass(to);}
if($.isFunction(callback)){callback(e);}});if($.isNumeric(duration)){$el.css("transition-duration",duration+"ms");}
if($.isPlainObject(to)){if(to.scaleX!==undefined&&to.scaleY!==undefined){final=$.extend({},to,{width:$el.width()*to.scaleX,height:$el.height()*to.scaleY,scaleX:1,scaleY:1});delete to.width;delete to.height;if($el.parent().hasClass("fancybox-slide--image")){$el.parent().addClass("fancybox-is-scaling");}}
$.fancybox.setTranslate($el,to);}else{$el.addClass(to);}
$el.data("timer",setTimeout(function(){$el.trigger("transitionend");},duration+16));},stop:function($el){if($el&&$el.length){clearTimeout($el.data("timer"));$el.off("transitionend").css("transition-duration","");$el.parent().removeClass("fancybox-is-scaling");}}};function _run(e,opts){var items=[],index=0,$target,value;if(e&&e.isDefaultPrevented()){return;}
e.preventDefault();opts=e&&e.data?e.data.options:opts||{};$target=opts.$target||$(e.currentTarget);value=$target.attr("data-fancybox")||"";if(value){items=opts.selector?$(opts.selector):e.data?e.data.items:[];items=items.length?items.filter('[data-fancybox="'+value+'"]'):$('[data-fancybox="'+value+'"]');index=items.index($target);if(index<0){index=0;}}else{items=[$target];}
$.fancybox.open(items,opts,index);}
$.fn.fancybox=function(options){var selector;options=options||{};selector=options.selector||false;if(selector){$("body").off("click.fb-start",selector).on("click.fb-start",selector,{options:options},_run);}else{this.off("click.fb-start").on("click.fb-start",{items:this,options:options},_run);}
return this;};$D.on("click.fb-start","[data-fancybox]",_run);$D.on("click.fb-start","[data-trigger]",function(e){_run(e,{$target:$('[data-fancybox="'+$(e.currentTarget).attr("data-trigger")+'"]').eq($(e.currentTarget).attr("data-index")||0),$trigger:$(this)});});})(window,document,window.jQuery||jQuery);